# See PwnPlantGrowth's page on http://dev.bukkit.org for more config details.

# which worlds should this plugin be enabled in? worlds not in this list will have default growth.
enabled_worlds:
  - world
  - world_nether

# stop buckets and dispensers from transporting source blocks - adds realism
block_water_bucket: false
    
# natural sky light level: 0 allows any, 10 is sunlight through glass/tree leaves, 15 is direct sunlight
min_natural_light: 10

# list of items allowed to grow in false light (torches, lightstone, lava) - use offical MATERIAL names to add to this list
grow_in_dark: 
  - RED_MUSHROOM
  - BROWN_MUSHROOM
  - NETHER_WARTS
  - COCOA 

# run a debug log to view additional plugin data for troubleshooting and configuration, turn off in production!
debug_log: false

# CROPS
Cactus:
    Growth: 50
    Death: 5
    Biome: 
    - DESERT
    - DESERT_HILLS
Carrot: 
    Growth: 50
    Death: 5
    Biome: []
Cocoa: 
    Growth: 25
    Death: 5
    Biome:
    - JUNGLE
    - JUNGLE_HILLS
Melon_Block: 
    Growth: 50
    Biome: []
Melon_Stem:
    Growth: 50
    Death: 5
    Biome: []
Nether_Wart:
    Growth: 25
    Death: 5
    Biome: 
    - HELL
Potato:
    Growth: 50
    Death: 5
    Biome: []
Pumpkin_Block:
    Growth: 50
    Biome: []
Pumpkin_Stem:
    Growth: 50
    Death: 5
    Biome: []
Sugar_Cane:
    Growth: 50
    Death: 5
    Biome:
    - BEACH
    - SWAMPLAND
Wheat:
    Growth: 50
    Death: 5
    Biome:
    - PLAINS
    - RIVER

# TREES
Birch:
    Growth: 50
    Death: 5
    Biome: []
Jungle:
    Growth: 50
    Death: 5
    Biome:
    - JUNGLE
    - JUNGLE_HILLS    
Spruce:
    Growth: 50
    Death: 5
    Biome:
    - FOREST
    - FOREST_HILLS
    - TAIGA
    - TAIGA_HILLS
Tree:
    Growth: 50
    Death: 5
    Biome: []

# BIG TREE
Big_Tree:
    Growth: 50
    Death: 5
    Biome: []

# GIANT MUSHROOMS
Brown_Mushroom:
    Growth: 50
    Death: 5
    Biome:
    - MUSHROOM_ISLAND
    - MUSHROOM_SHORE
Red_Mushroom:
    Growth: 50
    Death: 5
    Biome:
    - MUSHROOM_ISLAND
    - MUSHROOM_SHORE
      