# See PwnPlantGrowth's page on http://dev.bukkit.org for more config details.
# Full biome list available at http://jd.bukkit.org/dev/apidocs/org/bukkit/block/Biome.html

# which worlds should this plugin be enabled in? worlds not in this list will have default growth.
enabled_worlds:
  - example_world
  - example_world_nether

# stop buckets and dispensers from transporting source blocks - adds realism
block_water_bucket: false
block_water_dispenser: false
    
# natural sky light level: 0 allows any, 10 is sunlight through glass/tree leaves, 15 is direct sunlight
min_natural_light: 10

# list of items allowed to grow in false light (torches, lightstone, lava) - use offical MATERIAL names to add to this list
grow_in_dark: 
  - RED_MUSHROOM
  - BROWN_MUSHROOM
  - NETHER_WARTS
  - COCOA 

# run a debug log to view additional plugin data for troubleshooting and configuration, turn off in production!
debug_log: false

# CROPS
Cactus:
    Growth: 50
    Death: 5
    Biome: 
    - DESERT
    - DESERT_HILLS
Carrot: 
    Growth: 50
    Death: 5
    Biome: 
    - PLAINS
    - DESERT
    PLAINS: 
      Growth: 100
      Death: 0 
    DESERT:
      Growth: 25
      Death: 50
Cocoa: 
    Growth: 25
    Death: 5
    Biome:
    - JUNGLE
    - JUNGLE_HILLS
Melon_Block: 
    Growth: 50
    Biome: []
Melon_Stem:
    Growth: 50
    Death: 5
    Biome: []
Nether_Wart:
    Growth: 25
    Death: 5
    Biome: 
    - HELL    
Potato:
    Growth: 50
    Death: 5
    Biome: []
Pumpkin_Block:
    Growth: 50
    Biome: []
Pumpkin_Stem:
    Growth: 50
    Death: 5
    Biome: []
Sugar_Cane:
    Growth: 50
    Death: 5
    Biome:
    - BEACH
    - RIVER
    - SWAMPLAND   
Wheat:
    Growth: 50
    Death: 5
    Biome:
    - PLAINS
    - RIVER

# TREES
Acacia:
    Growth: 50
    Death: 5
    Biome:
    - SAVANNA
    - SAVANNA_MOUNTAINS
    - SAVANNA_PLATEAU
    - SAVANNA_PLATEAU_MOUNTAINS
Birch:
    Growth: 50
    Death: 5
    Biome: []
Jungle:
    Growth: 50
    Death: 5
    Biome:
    - JUNGLE
    - JUNGLE_HILLS  
Oak:
    Growth: 50
    Death: 5
    Biome: 
    - ROOFED_FOREST        
    - ROOFED_FOREST_MOUNTAINS   
Spruce:
    Growth: 50
    Death: 5
    Biome:
    - FOREST
    - FOREST_HILLS
    - TAIGA
    - TAIGA_HILLS
Tree:
    Growth: 50
    Death: 5
    Biome: []

# BIG TREE
Big_Tree:
    Growth: 50
    Death: 5
    Biome: []

# GIANT MUSHROOMS
Brown_Mushroom:
    Growth: 50
    Death: 5
    Biome:
    - MUSHROOM_ISLAND
    - MUSHROOM_SHORE
Red_Mushroom:
    Growth: 50
    Death: 5
    Biome:
    - MUSHROOM_ISLAND
    - MUSHROOM_SHORE
      