# See PwnPlantGrowth's page on https://dev.bukkit.org for more config details.

# CROPS
CACTUS: 50
CARROT: 50
COCOA: 50
MELON: 50
MELON_STEM: 50
NETHERWART: 25
POTATO: 50
PUMPKIN: 50
PUMPKIN_STEM: 50
SUGAR_CANE: 50
WHEAT: 50

# TREES
BIRCH: 50
JUNGLE: 50
SPRUCE: 50
TREE: 50

# BIG TREE
BIG_TREE: 25

# GIANT MUSHROOMS
BROWN_MUSHROOM: 50
RED_MUSHROOM: 50