# See PwnPlantGrowth's page on http://dev.bukkit.org for more config details.

# Full biome list available at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/block/Biome.html

# Plants / Crops are available in the "Material" list. See the following for official material names.
# Full material list available at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html

# Which worlds should this plugin be enabled in? Worlds not in this list will have default growth.
enabled_worlds:
  - example_world
  - example_world_nether
  
# Natural sky light level: 0 allows any, 10 is sunlight through glass/tree leaves, 15 is direct sunlight
min_natural_light: 10

# List of items allowed to grow in false light (torches, lightstone, lava) - use offical MATERIAL names to add to this list
grow_in_dark: 
  - RED_MUSHROOM
  - BROWN_MUSHROOM
  - NETHER_WARTS
  - COCOA 

# Enable use of weed killer
weed_killer_enabled: false

# A Block that can act as a weed killer (keeps plants from dying, will NOT affect growth rates)
weed_killer: GOLD_BLOCK

# Radius that weed killer protects, plants within this distance of the weed killer block will not turn to dead shrubs
weed_killer_radius: 5

# Enable use of fertilizer
fertilizer_enabled: false

# A Block that can act as a fertilizer (keeps plants growing at 100% or rate set below - as long as they are in the right biome)
fertilizer: SOUL_SAND

# Radius that fertilizer affects, plants within this distance of the block will grow at 100% or rate set below
fertilizer_radius: 5

# Set the fertilizer rate of growth globally when a fertilizer block is nearby, defaults to 100% 
# note that specific plant/biome dark rates and death rates take effect regardless of fertilizer 
fertilizer_rate: 100

# Enable use of UV Light Block
uv_enabled: false

# A Block that can act as UV Light (will allow plants in radius to grow where there is no natural light, -note, still requires actual lighting)
uv: GLOWSTONE

# Radius that UV affects
uv_radius: 5

# Allow plugin to capture bonemeal (only works for trees right now)
limit_bonemeal: false

# Run a debug log to view additional plugin data for troubleshooting and configuration, turn off in production!
debug_log: false

# Set true if you want also to log the coordinates on the world of the event - gets spammy
log_coords: false

# BIOME GROUPS - You can MAKE YOUR OWN versions of these, this is just a sample set of groups
BiomeGroup:
    GreatGrowing:
    - BEACHES
    - BIRCH_FOREST
    - FOREST
    - JUNGLE
    - JUNGLE_EDGE
    - MUSHROOM_ISLAND
    - MUSHROOM_ISLAND_SHORE
    - PLAINS
    - RIVER
    - SAVANNA
    - SWAMPLAND
    GoodGrowing: 
    - BIRCH_FOREST_HILLS
    - FOREST_HILLS
    - JUNGLE_HILLS
    - MESA
    - ROOFED_FOREST
    - TAIGA
    - REDWOOD_TAIGA
    - REDWOOD_TAIGA_HILLS
    - TAIGA_HILLS
    BadGrowing:
    - COLD_BEACH
    - DESERT
    - DESERT_HILLS
    - EXTREME_HILLS
    - EXTREME_HILLS_WITH_TREES
    - FROZEN_RIVER
    - ICE_FLATS
    - ICE_MOUNTAINS
    - MESA_CLEAR_ROCK
    - MESA_ROCK
    - SAVANNA_ROCK
    - STONE_BEACH
    - TAIGA_COLD
    - TAIGA_COLD_HILLS
    NoGrowing:
    - VOID
    - SKY
    - HELL

# CROPS - Important note, as of PPG 1.6 the plant names are now all in UPPER CASE matching the actual Bukkit Material.TYPE 

# In this example beetroot only grows in GoodGrowing and GreatGrowing biomes, setting biome NONE should block all others
BEETROOTS: 
    Growth: 50
    GrowthDark: 25
    Death: 5
    DeathDark: 25 
    BiomeGroup:
    - GreatGrowing
    - GoodGrowing 
    GreatGrowing:
      Growth: 100
      GrowthDark: 75
      Death: 0 
      DeathDark: 5     
    GoodGrowing:
      Growth: 80
      GrowthDark: 55
      Death: 5 
      DeathDark: 10  
    Biome:
    - NONE 

# In this example cactus is restricted to specific biomes
CACTUS:
    Growth: 50
    GrowthDark: 25
    Death: 5
    DeathDark: 25
    Biome: 
    - DESERT
    - DESERT_HILLS
    - SAVANNA

# Carrot example is setup like beetroot but also grows in desert by setting Biome: - DESERT value
CARROT: 
    Growth: 50
    GrowthDark: 25
    Death: 5
    DeathDark: 25    
    BiomeGroup:
    - GreatGrowing
    - GoodGrowing 
    GreatGrowing:
      Growth: 100
      GrowthDark: 75
      Death: 0 
      DeathDark: 5     
    GoodGrowing:
      Growth: 80
      GrowthDark: 55
      Death: 5 
      DeathDark: 10      
    Biome: 
    - DESERT
    DESERT:
      Growth: 25
      Death: 50

# In this example Cocoa will only grow in jungle biomes at 25% normal rate
COCOA: 
    Growth: 25
    Death: 5
    Biome:
    - JUNGLE
    - JUNGLE_HILLS
    - JUNGLE_EDGE 

# In this example kelp will grow anywhere - Biome: [] - but only at 50%
KELP_PLANT: 
    Growth: 50
    Death: 5
    Biome: []

# In this example melons will grow anywhere - Biome: [] - but only at 50%
MELON: 
    Growth: 50
    Death: 5
    Biome: []

# This is the stem portion, it can be set to grow differently than the melon/pumpkin
MELON_STEM:
    Growth: 50
    Death: 5
    Biome: []

# In this example netherwart is restricted to the nether at 25%
NETHER_WART_BLOCK:
    Growth: 25
    Death: 5
    Biome: 
    - HELL
        
# Potato will grow in great and good areas, all others at its default rate with Biome: []
POTATO:
    Growth: 50
    GrowthDark: 25
    Death: 5
    DeathDark: 25 
    BiomeGroup:
    - GreatGrowing
    - GoodGrowing 
    GreatGrowing:
      Growth: 100
      GrowthDark: 75
      Death: 0 
      DeathDark: 5     
    GoodGrowing:
      Growth: 80
      GrowthDark: 55
      Death: 5 
      DeathDark: 10
    Biome: []

PUMPKIN:
    Growth: 50
    Death: 5    
    Biome: []

# This is the stem portion, it can be set to grow differently than the melon/pumpkin
PUMPKIN_STEM:
    Growth: 50
    Death: 5
    Biome: []

# In this example sugar cane will only grow in these biomes at a 50% rate and no where else    
SUGAR_CANE:
    Growth: 50
    Death: 5
    Biome:
    - BEACHES
    - BEACH
    - RIVER
    - SWAMPLAND  
    
# This is WHEAT - In this example wheat will grow everywhere at 50% rate, and at better rates in great and good growing groups
WHEAT:
    Growth: 50
    GrowthDark: 25
    Death: 5
    DeathDark: 25 
    BiomeGroup:
    - GreatGrowing
    - GoodGrowing 
    GreatGrowing:
      Growth: 100
      GrowthDark: 75
      Death: 0 
      DeathDark: 5     
    GoodGrowing:
      Growth: 80
      GrowthDark: 55
      Death: 5 
      DeathDark: 10
    Biome: []
      
# TREES 
# Full tree list available at https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/TreeType.html

ACACIA:
    Growth: 50
    Death: 5
    Biome:
    - SAVANNA
    - SAVANNA_MOUNTAINS
    - SAVANNA_PLATEAU
    - SAVANNA_PLATEAU_MOUNTAINS

BIG_TREE:
    Growth: 50
    Death: 5
    Biome: []

BIRCH:
    Growth: 50
    Death: 5
    Biome: []

BROWN_MUSHROOM:
    Growth: 50
    Death: 5
    Biome:
    - MUSHROOM_ISLAND
    - MUSHROOM_SHORE
    
CHORUS_PLANT:
    Growth: 50
    Death: 5
    Biome: []

COCOA_TREE:
    Growth: 50
    Death: 5
    Biome: []
          
DARK_OAK:
    Growth: 50
    Death: 5
    Biome: 
    - ROOFED_FOREST        
    - ROOFED_FOREST_MOUNTAINS          
    
JUNGLE:
    Growth: 50
    Death: 5
    Biome:
    - JUNGLE
    - JUNGLE_HILLS  

JUNGLE_BUSH:
    Growth: 50
    Death: 5
    Biome:
    - JUNGLE
    - JUNGLE_HILLS      

MEGA_REDWOOD:
    Growth: 50
    Death: 5
    Biome:
    - FOREST
    - FOREST_HILLS
    - TAIGA
    - TAIGA_HILLS    
    
RED_MUSHROOM:
    Growth: 50
    Death: 5
    Biome:
    - MUSHROOM_ISLAND
    - MUSHROOM_SHORE
    
REDWOOD:
    Growth: 50
    Death: 5
    Biome:
    - FOREST
    - FOREST_HILLS
    - TAIGA
    - TAIGA_HILLS

SMALL_JUNGLE:
    Growth: 50
    Death: 5
    Biome:
    - JUNGLE
    - JUNGLE_HILLS  

SWAMP:
    Growth: 50
    Death: 5
    Biome: []
        
TALL_BIRCH:
    Growth: 50
    Death: 5
    Biome: []
    
TALL_REDWOOD:
    Growth: 50
    Death: 5
    Biome:
    - FOREST
    - FOREST_HILLS
    - TAIGA
    - TAIGA_HILLS
        
TREE:
    Growth: 50
    Death: 5
    Biome: []
          
# Plugin will check for the following list of plants as of ver. 2.4.0
# Plants: "BEETROOTS", "CACTUS", "CARROT", "COCOA", GRASS", "KELP_PLANT", "MELON", "MELON_STEM", "NETHER_WARTS", "POTATO", "PUMPKIN", "PUMPKIN_STEM", "SUGAR_CANE", "WHEAT"
# Trees: "ACACIA", "BIG_TREE", "BIRCH", "BROWN_MUSHROOM", "COCOA_TREE", "CHORUS_PLANT", "DARK_OAK", "JUNGLE", "JUNGLE_BUSH", "MEGA_REDWOOD", "RED_MUSHROOM", "REDWOOD", "SMALL_JUNGLE", "SWAMP", "TALL_BIRCH", "TALL_REDWOOD", "TREE"